# Generated by Django 6.0.1 on 2026-01-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, help_text='Business employee identifier', max_length=50, unique=True),
        ),
    ]
